# .streamlit/secrets.toml
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"
TRANSLATION_MODEL_PROVIDER = "Gemini" # Default, can be "Ollama" or "vLLM"
OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_MODEL_NAME = "llama2" # E.g., llama2, gemma:2b
VLLM_BASE_URL = "http://localhost:8000"
